name: Name Probe
on:
  workflow_dispatch:
    inputs:
      go:
        default: "no"
jobs:
  r:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.s.outputs.run }}
    steps:
      - id: s
        run: echo "run=${{ inputs.go }}" >> "$GITHUB_OUTPUT"
  skipped-with-dynamic-name:
    needs: r
    if: needs.r.outputs.run == 'yes'
    name: ${{ needs.r.outputs.run == 'yes' && 'Probe Real' || 'Probe Not Needed' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo hi
  noop-with-dynamic-name:
    needs: r
    name: ${{ needs.r.outputs.run == 'yes' && 'Probe2 Real' || 'Probe2 Not Needed' }}
    runs-on: ubuntu-latest
    steps:
      - if: needs.r.outputs.run == 'yes'
        run: echo real
